### ISSUE TITLE
Cannot install latest versions 2.1.0 or 2.0.0 - C++ compilation error

### ISSUE THREAD

**Issue by kristjanmoore** [nesscoder/fasano.franceschini.test#11]
Hi, when I try to install either version 2.1.0 or 2.0.0 of the package, the installation fails due to a compilation error regarding the following line of code in `ff_internal_functions.cpp`:

```
ff_internal_functions.cpp:21:49: error: no matching function for call to 'max(double&, int)'
d = std::max(d, abs(c1[i]/n1 - c2[i]/n2));
```

The full error/warning message is very long; unfortunately, I can't copy-and-paste from the machine on which I got the failure, so I'm going to paraphrase it. It repeatedly mentions the above line of code while also complaining about `template argument deduction/substitution failed` and `mismatched types 'std::initializer_list<_Tp>' and 'double'` and `deduced conflicting types for parameter 'const _Tp' ('double' and 'int')`. 

Installing version 1.1.0 with `devtools::install_version('fasano.franceschini.test', version = '1.1.0')` doesn't produce the above error and seems to work fine.

**Comment by cpuritz** [comment]
Hi, thanks for bringing this to our attention. I pushed a tentative fix, please try downloading the development version and let me know if the error persists.

**Comment by kristjanmoore** [comment]
Fix works for me! Thanks.
