### ISSUE TITLE
Problem with n = 1000 in the given example. 

### ISSUE THREAD

**Issue by amithgovind** [nesscoder/fasano.franceschini.test#6]
Hi Elan, 
First of all thanks a lot for creating this project.
I would like to request your help with a small problem that I'm having:

When I use the example case but with n = 1000 for all of them. 
The p-value is very low even though the underlying distributions are the same.
However, when I increase the n to 1500, the p-value is high again. 
Please let me know if this problem occurs only in my computer or if you also have the same problem. 

I have pasted the output from Rstudio below.
Thanks a lot for your time.

Kind regards,
Amith 
################################################################################
################################################################################
 library(fasano.franceschini.test)

set.seed(0)

S1 <- data.frame(x = rnorm(n = 1000, mean = 0, sd = 1),
                 y = rnorm(n = 1000, mean = 0, sd = 3))

S2 <- data.frame(x = rnorm(n = 1000, mean = 0, sd = 1),
                  y = rnorm(n = 1000, mean = 0, sd = 3))

fasano.franceschini.test(S1, S2, seed = 0)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
       Fasano-Francheschini Test

data:  S1 and S2
Z = 1.923, p-value = 0.0297
95 percent confidence interval:
 0.00616786 0.08435690
sample estimates:
   D1    D2 
0.089 0.083 
################################################################################

################################################################################
################################################################################

library(fasano.franceschini.test)

set.seed(0)

S1 <- data.frame(x = rnorm(n = 1500, mean = 0, sd = 1),
                  y = rnorm(n = 1500, mean = 0, sd = 3))

S2 <- data.frame(x = rnorm(n = 1500, mean = 0, sd = 1),
                  y = rnorm(n = 1500, mean = 0, sd = 3))

fasano.franceschini.test(S1, S2, seed = 0)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
	Fasano-Francheschini Test

data:  S1 and S2
Z = 1.0498, p-value = 0.8614
95 percent confidence interval:
 0.7783773 0.9220964
sample estimates:
        D1         D2 
0.03800000 0.03866667 
################################################################################

**Comment by amithgovind** [comment]
Sorry for the messed up format.  I didn't know that this was going to happen.

**Comment by nesscoder** [comment]
Hi Amith, 

Thanks for your question. The output you are getting is not actually a bug in the code, but rather comes down to statistical theory and the definition of a p-value.

When you run the above code, you will randomly select two sets of 1000 points from an underlying distribution that is the same. While we know the ground truth, when we randomly sample from this distribution the outcome of the statistical test will be dependent on the points selected. In the case of using the same underlying distribution, we will either get a true negative (they are NOT from different underlying distribution, what we expect to happen) or a false positive (they are said to be from different underlying distributions, even though we know they are from the same underlying distribution).

For example: In this case, we randomly pull a set of points, assess their difference using the fasano franceschini statistic, and use this to calculate a p-value. This p-value is defined as the chance of sampling some data as or more extreme than the data sampled. In this case this p-value is  0.0297. It just happens that when you use a seed of zero, by random chance you got a set of points that are quite different from each other -- plot these points in 2D distribution in R for a sanity check -- even through they were being drawn from the same underlying distribution. This outcome would be considered a false positive.

```
data <- dplyr::bind_rows(list(S1=S1, S2=S2), .id = 'source')

library(ggplot2)
ggplot(data, aes(x = x, y = y, color = source))+
  geom_point()
```

We can run this again, but with a different seed -- for instance if i was to set.seed(1234). Using this new seed, we choose a different set of random point that by the FF test are not statistically different from each other -- as we would expect from our underlying knowledge -- the true negative result referred to above. (Plot these points in 2D distribution in R for a sanity check)


```
> set.seed(1234)
> 
> S1 <- data.frame(x = rnorm(n = 1000, mean = 0, sd = 1),
+                  
+                  y = rnorm(n = 1000, mean = 0, sd = 3))
> S2 <- data.frame(x = rnorm(n = 1000, mean = 0, sd = 1),
+                  
+                  y = rnorm(n = 1000, mean = 0, sd = 3))
> fasano.franceschini.test(S1, S2, seed = 0)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
	Fasano-Francheschini Test

data:  S1 and S2
Z = 1.241, p-value = 0.4059
95 percent confidence interval:
 0.3093085 0.5082384
sample estimates:
   D1    D2 
0.055 0.056
```
The above concepts still applied when you pulled n = 1500 points, as well as you now have more points to have a more accurate assessment of the underlying distribution (think the central limit theorem). In this case, you got the expected result given that the underlying distributions are the same. To hammer home the point, you could also theoretically find a seed for the n = 1500 case where the points selected in the S1 and S2 distributions are quite different from each other, and would result in a p-value saying that the samples are pulled from different distributions (eg. a false positive).

Hope this is helpful and clears up any of your confusion!

Best,
Elan
